linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - ireturn
    - lll
    - paralleltest
    - thelper
  issues:
    exclude-rules:
      - path: (.+)_test.go
        linters:
          - gochecknoglobals
          - goconst
          - funlen
